# Travis doesn't support D...
# language: d
language: c

# Ubuntu's ldc package has not been maintained.
env:
 - DCOMPILER=dmd
 - DCOMPILER=gdc
# - DCOMPILER=ldc

install: sh .travis-install.sh

script: dub run --build=unittest --compiler="$DCOMPILER" <sample.txt
